default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: CakeCae_development

test:
  <<: *default
  database: CakeCae_test

production:
  <<: *default
  database: CakeCae_production
  username: CakeCae
  password: <%= ENV["CAKECAE_DATABASE_PASSWORD"] %>
